src/XD.UI.Site/Models/Aluno.cs
namespace XD.UI.Site.Models
{
    public class Aluno
    {
        public Aluno()
        {   
            Id = Guid.NewGuid();
        }
        public Guid Id { get; set; }
        public string? Nome { get; set; }
        public string? Email { get; set; }
        public DateTime DataNascimento { get; set; } 
    }
}

src/XD.UI.Site/Models/Pedido.cs
using System;

namespace XD.UI.Site.Models
{
    public class Pedido
    {
        public Guid Id { get; set; }

        public Pedido()
        {
            Id = Guid.NewGuid();
        }
    }
}

src/XD.UI.Site/Areas/Produtos/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Mvc;

namespace XD.UI.Site.Areas.Produtos.Controllers
{
    public class CadastroController : Controller
    {
        [Area("Produtos")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/XD.UI.Site/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using XD.UI.Site.Data;

namespace XD.UI.Site.Controllers
{
    public class HomeController : Controller
    {
        private IPedidoRepository _pedidoRepository;               
        public HomeController(IPedidoRepository pedidoRepository)
        {
            _pedidoRepository = pedidoRepository;
        }
        public IActionResult Index()
        {
            var pedido = _pedidoRepository.ObterPedido();
            return View();
        }
    }
}

src/XD.UI.Site/Controllers/TestCrudController.cs
using Microsoft.AspNetCore.Mvc;
using XD.UI.Site.Data;
using XD.UI.Site.Models;

namespace XD.UI.Site.Controllers
{
	public class TestCrudController : Controller
	{
		private readonly MeuDbContext _contexto;
		public TestCrudController(MeuDbContext contexto)
		{
			_contexto = contexto;
		}

		public IActionResult Index()
		{
			
			var aluno = new Aluno
			{
				Nome = "Eduardo",
				DataNascimento = DateTime.Now,
				Email = "domingues-pc@hotmail.com"
			};

			_contexto.Alunos.Add(aluno);
			_contexto.SaveChanges();
									
			var aluno2 = _contexto.Alunos.Find(aluno.Id);
			var aluno3 = _contexto.Alunos.FirstOrDefault(a => a.Email == "domingues-pc@hotmail.com");
			var aluno4 = _contexto.Alunos.Where(a => a.Email == "domingues-pc@hotmail.com");

			aluno.Nome = "João";
			_contexto.Alunos.Update(aluno);
            _contexto.SaveChanges();

			_contexto.Alunos.Remove(aluno);
			_contexto.SaveChanges();

			return View();
		}
	}
}

src/XD.UI.Site/Controllers/TesteCrudController.cs
using Microsoft.AspNetCore.Mvc;
using XD.UI.Site.Data;
using XD.UI.Site.Models;

namespace XD.UI.Site.Controllers
{
	public class TesteCrudController : Controller
	{
		private readonly MeuDbContext _contexto;
		public TesteCrudController(MeuDbContext contexto)
		{
			_contexto = contexto;
		}

		public IActionResult Index()
		{
			
			var aluno = new Aluno
			{
				Nome = "Eduardo",
				DataNascimento = DateTime.Now,
				Email = "domingues-pc@hotmail.com"
			};

			_contexto.Alunos.Add(aluno);
			_contexto.SaveChanges();
									
			var aluno2 = _contexto.Alunos.Find(aluno.Id);
			var aluno3 = _contexto.Alunos.FirstOrDefault(a => a.Email == "domingues-pc@hotmail.com");
			var aluno4 = _contexto.Alunos.Where(a => a.Email == "domingues-pc@hotmail.com");

			aluno.Nome = "João";
			_contexto.Alunos.Update(aluno);
            _contexto.SaveChanges();

			_contexto.Alunos.Remove(aluno);
			_contexto.SaveChanges();

			return View("_ValidationScriptsPartial");
		}
	}
}

src/XD.UI.Site/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/XD.UI.Site/Views/Home/Index.cshtml
@using XD.UI.Site.Data
@inject IPedidoRepository PedidoRepository

@PedidoRepository.ObterPedido().Id

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/XD.UI.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XD.UI.Site</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/XD.UI.Site.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">XD.UI.Site</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="Index">Cadastro</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Vendas" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                        </li> 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
               <email email-domain="gmail.com">Contato</email>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>